name: Deploy Site

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 19
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build
